[workspace]
members = ["cosmic-settings", "page", "pages/*"]
default-members = ["cosmic-settings"]
resolver = "2"
rust-version = "1.71.0"
sunrise_sunset = "1.0.1"

[workspace.dependencies]
cosmic-randr = { git = "https://github.com/pop-os/cosmic-randr" }
tokio = { version = "1.37.0", features = ["macros"] }

[workspace.dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
features = ["dbus-config", "single-instance", "tokio", "wayland", "wgpu", "xdg-portal"]

[workspace.dependencies.cosmic-config]
git = "https://github.com/pop-os/libcosmic"
features = ["dbus"]

[workspace.dependencies.cosmic-bg-config]
git = "https://github.com/pop-os/cosmic-bg"

[workspace.dependencies.cosmic-comp-config]
git = "https://github.com/pop-os/cosmic-comp"

[workspace.dependencies.cosmic-panel-config]
git = "https://github.com/pop-os/cosmic-panel"

[workspace.dependencies.cosmic-randr-shell]
git = "https://github.com/pop-os/cosmic-randr"

[workspace.dependencies.sctk]
git = "https://github.com/smithay/client-toolkit/"
package = "smithay-client-toolkit"
rev = "3bed072"

[profile.release]
opt-level = 3

[patch.'https://github.com/smithay/client-toolkit/']
smithay-client-toolkit = { git = "https://github.com/smithay/client-toolkit//", rev = "3bed072" }

[patch.'https://github.com/pop-os/cosmic-protocols']
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols//", rev = "1316f9e" }

# For development and testing purposes
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
