[workspace]
members = ["app", "page", "pages/*"]
default-members = ["app"]

[workspace.dependencies.iced_core]
git = "https://github.com/pop-os/libcosmic"

[workspace.dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
features = ["wayland", "tokio", "single-instance"]

[workspace.dependencies.cosmic-config]
git = "https://github.com/pop-os/libcosmic"

[workspace.dependencies.cosmic-bg-config]
git = "https://github.com/pop-os/cosmic-bg"

[workspace.dependencies.cosmic-comp-config]
git = "https://github.com/pop-os/cosmic-comp"
# path = "../cosmic-comp/cosmic-comp-config"

[workspace.dependencies.cosmic-panel-config]
git = "https://github.com/pop-os/cosmic-panel"

[patch."https://github.com/pop-os/libcosmic"]
# libcosmic = { git = "https://github.com/pop-os/libcosmic//", branch = "single-instance" }
# cosmic-config = { git = "https://github.com/pop-os/libcosmic//", branch = "single-instance"}

[patch."https://github.com/Smithay/client-toolkit"]
sctk = { git = "https://github.com/smithay/client-toolkit//", package = "smithay-client-toolkit", rev = "e63ab5f"}

[profile.release]
opt-level = 3
lto = "thin"
