[package]
name = "cosmic-settings"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
bytesize = "1.1.0"
cascade = "1.0.0"
fuzzy-matcher = "0.3.7"
gtk4 = { version = "0.3.1", features = ["v4_4"] }
once_cell = "1.9.0"
os-release = "0.1.0"
sysinfo = "0.22.5"
cosmic-dbus-networkmanager = { git = "https://github.com/pop-os/dbus-settings-bindings" }
tokio = { version = "1.15.0", features = ["full"] }
zbus = "2.0.1"
futures = "0.3.19"
futures-util = "0.3.19"
tokio-stream = "0.1.8"
zvariant = "3.0.0"
anyhow = "1.0.52"
relm4-macros = "0.4.1"

[build-dependencies]
grass = "0.10.8"