[package]
name = "cosmic-settings-sound-subscription"
version = "1.0.0-beta1"
edition = "2024"
rust-version.workspace = true
license = "MPL-2.0"
publish = true

[dependencies]
async-fn-stream = "0.3.2"
futures = "0.3.31"
indexmap = "2.12.0"
libcosmic = { git = "https://github.com/pop-os/libcosmic" }
libpulse-binding = "2.30.1"
log = "0.4.28"
pipewire = "0.8"
rustix = "1.1.2"
tokio = "1.48.0"
tracing = "0.1.41"
