[package]
name = "cosmic-settings-sound-subscription"
version = "1.0.0-beta1"
edition = "2024"
rust-version.workspace = true
license = "MPL-2.0"
publish = true

[dependencies]
async-fn-stream = "0.3.2"
futures = "0.3.31"
indexmap = "2.11.4"
intmap = "3.1.2"
libcosmic = { git = "https://github.com/pop-os/libcosmic" }
libpulse-binding = "2.30.1"
libspa = "0.9.2"
libspa-sys = "0.9.2"
log = "0.4.28"
numtoa = "1.0.0-alpha1"
pipewire = "0.9"
rustix = "1.0.8"
tokio = "1.47.1"
tracing = "0.1.41"
