[package]
name = "cosmic-settings-page"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_setters = "0.1.6"
regex = "1.11.1"
slotmap = "1.0.7"
libcosmic = { workspace = true }
downcast-rs = "1.2.1"
once_cell = "1.20.3"
tokio.workspace = true
url = "2.5.4"
slab = "0.4.9"
