[package]
name = "cosmic-settings-page"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_setters = "0.1.6"
regex = "1.10.5"
slotmap = "1.0.7"
libcosmic = { workspace = true }
generator = "0.7.5"
downcast-rs = "1.2.1"
once_cell = "1.19.0"
tokio.workspace = true
url = "2.5.2"
slab = "0.4.9"
