[package]
name = "cosmic-settings-page"
version = "1.0.2"
edition = "2024"

[dependencies]
derive_setters = "0.1.8"
regex = "1.12.2"
slotmap = "1.1.1"
libcosmic = { workspace = true }
downcast-rs = "2.0.2"
url = "2.5.8"
slab = "0.4.11"
